# # Create App deployment
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: auth-app
#   namespace: egeeks
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: auth-app
#   template:
#     metadata:
#       labels:
#         app: auth-app
#     spec:
#       containers:
#       - name: auth-app
#         image: registry.deti:5000/hugom/auth-app
#         ports:
#           - containerPort: 5001
          
# # Create Service for APP
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: auth-app
#   namespace: egeeks
# spec:
#   ports:
#   - port: 5001
#     targetPort: 5001
#   selector:
#     app: auth-app

# # Configure Traefik
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: auth-app-k3s
#   namespace: egeeks
#   annotations:
#     kubernetes.io/ingress.class: traefik
#     traefik.ingress.kubernetes.io/frontend-entry-points: http,https
#     traefik.ingress.kubernetes.io/redirect-entry-point: https
#     traefik.ingress.kubernetes.io/redirect-permanent: "true"
# spec:
#   rules:
#   - host: hugom-auth.egs
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: auth-app
#             port: 
#               number: 5001


# Create App deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-app
  namespace: egeeks
spec:
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
      - name: auth-app
        image: registry.deti:5000/hugom/auth-api:latest
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8006
        env:
        #- name: MARIADB_RANDOM_ROOT_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hugo-mysql-secret
              key: rootpassword
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hugo-mysql-secret
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: hugo-mysql-secret
              key: database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: hugo-mysql-secret
              key: user
      #   volumeMounts:
      #     - name: images-static
      #       mountPath: /app/www/images
      # restartPolicy: Always
      # volumes:
      #   - name: images-static
      #     persistentVolumeClaim:
      #       claimName: hugom-images-pvc

# Create Service for APP
---
apiVersion: v1
kind: Service
metadata:
  name: auth-app
  namespace: egeeks
spec:
  ports:
  - port: 8006
    targetPort: 8006
  selector:
    app: auth-app

# Configure Traefik
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-app-k3s
  namespace: egeeks
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: https,http
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    traefik.ingress.kubernetes.io/custom-request-headers: "Access-Control-Allow-Origin:*||Access-Control-Allow-Methods:DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT||Access-Control-Allow-Headers:access-control-allow-credentials,access-control-allow-headers,access-control-allow-origin,auth,content-type||Access-Control-Expose-Headers:access-control-allow-credentials,access-control-allow-headers,access-control-allow-origin,auth,content-type"
    traefik.ingress.kubernetes.io/custom-response-headers: "Access-Control-Allow-Origin:*||Access-Control-Allow-Methods:DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT||Access-Control-Allow-Headers:access-control-allow-credentials,access-control-allow-headers,access-control-allow-origin,auth,content-type||Access-Control-Expose-Headers:access-control-allow-credentials,access-control-allow-headers,access-control-allow-origin,auth,content-type"
spec:
  rules:
  - host: hugom.egs
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: auth-app
            port: 
              number: 8006