apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hugom-db-pvc
  namespace: hugom
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi