# Generated by Django 4.0.3 on 2022-04-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('photo', models.ImageField(blank=True, default='static/img/products/product_default.jpg', upload_to='./static/img/products/')),
                ('category', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
        ),
    ]
