# Create App deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-app
  namespace: hugom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
      - name: auth-app
        image: registry.deti:5000/hugom/auth-app:v3
        ports:
          - containerPort: 8080

# Create nginx deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: hugom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: registry.deti:5000/hugom/nginx-proxy
          name: nginx
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
          
# Create Service for APP
---
apiVersion: v1
kind: Service
metadata:
  name: auth-app
  namespace: hugom
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: auth-app

# Create Service for NGINX
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: hugom
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx

# Configure Traefik
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-app-k3s
  namespace: hugom
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  rules:
  - host: auth.egs
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port: 
              number: 80
