apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tista-images-pvc
  namespace: egeeks
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi