# Create App deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentapi-db
  namespace: egeeks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentapi-db
  template:
    metadata:
      labels:
        app: paymentapi-db
    spec:
      containers:
      - name: paymentapi-db
        image: registry.deti:5000/zppinho/paymentapi-db:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3306 
        env:
        #- name: MARIADB_RANDOM_ROOT_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: rootpassword
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: user
        resources: {}
        volumeMounts:
          - name: db-static
            mountPath: /var/lib/mysql
      restartPolicy: Always
      volumes:
        - name: db-static
          persistentVolumeClaim:
            claimName: zppinho-mysql-db-pvc


# Create Service for APP
---
apiVersion: v1
kind: Service
metadata:
  name: paymentapi-db
  namespace: egeeks
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: paymentapi-db 