# Create App deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: papi
  namespace: zppinho
spec:
  replicas: 1
  selector:
    matchLabels:
      app: papi
  template:
    metadata:
      labels:
        app: papi
    spec:
      containers:
      - name: papi
        image: registry.deti:5000/zppinho/papi:latest
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 8000
# Create Service for APP
---
apiVersion: v1
kind: Service
metadata:
  name: papi
  namespace: zppinho
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: papi


#Configure Traefik
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: papi-k3s
  namespace: zppinho
  annotations:
    kubernetes.io/ingress.class: traefik
    #traefik.ingress.kubernetes.io/router.middlewares: zppinho-midheader@kubernetescrd
    traefik.ingress.kubernetes.io/frontend-entry-points: https,http
    #traefik.ingress.kubernetes.io/redirect-entry-point: http
    #ingress.kubernetes.io/enable-cors: "true"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/enable-cors: "true"
    traefik.ingress.kubernetes.io/cors-origins: "*"
    #traefik.ingress.kubernetes.io/cors-credentials: "true"
    #traefik.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, DELETE"
    #ingress.kubernetes.io/whitelist-x-forwarded-for: "true" 
    traefik.ingress.kubernetes.io/custom-request-headers: "Access-Control-Allow-Origin:*||Access-Control-Allow-Methods:DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT||Access-Control-Allow-Headers:access-control-allow-credentials,access-control-allow-headers,access-control-allow-origin,auth,content-type||Access-Control-Expose-Headers:access-control-allow-credentials,access-control-allow-headers,access-control-allow-origin,auth,content-type||auth:* *"
    traefik.ingress.kubernetes.io/custom-response-headers: "Access-Control-Allow-Origin:*||Access-Control-Allow-Methods:DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT||Access-Control-Allow-Headers:access-control-allow-credentials,access-control-allow-headers,access-control-allow-origin,auth,content-type||Access-Control-Expose-Headers:access-control-allow-credentials,access-control-allow-headers,access-control-allow-origin,auth,content-type||auth:* *"
spec:
  rules:
  - host: zppinho-papi.egs
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: papi
            port: 
              number: 8000
  tls:
  - hosts:
    - zppinho-papi.egs
    - zppinho-preact.egs
    secretName: whoami-secret