version: '3.7'

services:

  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: test
      MARIADB_USER : test
      MARIADB_DATABASE: test
      MARIADB_MYSQL_LOCALHOST_USER: localhost
    ports:
      - "3306:3306"

  app:
    image: payapi
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    environment:
      DB_NAME: test
      DB_HOST: test
      DB_USER: test
      DB_PASS: test
    ports:
      - "8000:8000"
    depends_on:
      - db