apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zppinho-mysql-db-pvc
  namespace: egeeks
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 512Mi
