apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zppinho-nginx-pvc
  namespace: zppinho
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 512Mi
